#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config external_bar all:0:38 \
  mouse_follows_focus on \
  focus_follows_mouse on \
  window_zoom_persist on \
  window_placement second_child \
  window_shadow float \
  window_opacity on \
  window_opacity_duration 0.3 \
  active_window_opacity 0.96 \
  normal_window_opacity 0.7 \
  window_animation_duration 0.3 \
  window_animation_easing ease_out_circ \
  insert_feedback_color 0xff9dd274 \
  split_ratio 0.50 \
  auto_balance off \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap \
  \
  top_padding 8 \
  bottom_padding 8 \
  left_padding 8 \
  right_padding 8 \
  window_gap 8

yabai -m rule --add app="^(Stickies|Media Viewer|About This Mac|Finder|Little Arc — Google|Stickies|Microsoft Word|Finder|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor|Preview)$" manage=off layer=below
yabai -m rule --add app="^Arc" opacity=1.0
yabai -m config layout bsp

echo "yabai configuration loaded.."
